### ISSUE TITLE
Side effect

### ISSUE THREAD

**Issue by mtrempoltsev** [tarantool/checks#10]
```
local checks = require('checks')

local function foo(x)
    print(x)
    checks({})
    print(x)
end

foo(nil)
```

output:

```
nil
table: 0x010860e2c8
```

So the checks changes the passed value.

**Comment by rosik** [comment]
It's not a bug, it's a feature. And it's even well [documented](https://github.com/tarantool/checks#table-type-qualifiers) 

```
When the optional argument is validated with the table type qualifier,
its value is set to an empty table. Thus it's safe to do:

function fn(options)
    checks({timeout = '?number'})
    options.timeout = options.timeout or 5.0
end

fn() -- ok
```

**Comment by Totktonada** [comment]
I think, side effects in checks should be considered as bugs.

**Comment by mtrempoltsev** [comment]
```
local function foo(x)
    checks({})
    if x ~= nil then
        print('checks broke my code')
    end
end

foo(nil)
```

**Comment by racktear** [comment]
I too think that this behavior doesn't allow to check if options were not actually passed at all, so I consider this a bug.

**Comment by rosik** [comment]
First of all, are you intended to check the table itself or it's content?
If you want to check the table without content, use `checks('?table')` - it will not change anything.

@mtrempoltsev @racktear  could you provide a better example, when it's important to distinguish nil from empty _options_ table?

The table type qualifier was designed to check options, not the table containing them.

**Comment by rosik** [comment]
Expression `check({})` is almost useless in real world: you can not pass it anything, but empty table.

```
foo() -- ok
foo({}) -- ok
foo({anything = 1}) -- error:  unexpected argument opts.anything to foo
```

It's very strange, but if you really want you function to accept only nils and empty tables, I would recomend
```
function foo(tbl)
    checks('?table')
    assert(next(tbl) == nil)
end
```

**Comment by mtrempoltsev** [comment]
```
function foo(opts)
    checks({
        opt_a = 'string',
        opt_b = 'number' })
end

foo() -- checks hide my error
```

```
local function foo(opts)
    checks({
        opt_a = 'string',
        opt_b = 'number' })
    if opts ~= nil then
        print('checks broke my code')
    end
end

foo(nil)
```

**Comment by rosik** [comment]
This is really a bug, and it was [fixed](https://github.com/tarantool/checks/pull/8) in version [2.1.1](https://github.com/tarantool/checks/blob/master/CHANGELOG.md#211---2018-08-22)
