### ISSUE TITLE
Add `type(expected_type) == function` check, to call a custom function without saving to checkers

### ISSUE THREAD

**Issue by d-enk** [tarantool/checks#39]
something like

```lua
function check_custom_type(v)
    return true or false, "custom_type"
end

function f(arg)
    checks(check_custom_type)
end
```

**Comment by yngvar-antonsson** [comment]
@d-enk Hello! What case are you trying to solve with this issue? Are ordinary table-content checkers not enough for you?

**Comment by d-enk** [comment]
This is useful in cases of dynamically generating templates with custom check logic for checks.
Maybe it's not really about type checking, more about validation, but it's still quite convenient to be able to have non-static check functions.

**Comment by filonenko-mikhail** [comment]
Sorry a lot — no plans for such feature. Gently closing.
