### ISSUE TITLE
Inconsistency in licensing

### ISSUE THREAD

**Issue by ligurio** [tarantool/checks#49]
- RPM spec - MIT
- Debian spec- MIT
- LICENSE - MIT
- luarocks spec - BSD

Initially, `checks` was a part of https://github.com/SierraWireless/luasched that has a license MIT.
Seems we need to change license from BSD to MIT in luarocks spec.

**Comment by Totktonada** [comment]
The story behind: https://github.com/fab13n/checks/issues/2 and https://github.com/tarantool/checks/pull/28.

> Seems we need to change license from BSD to MIT in luarocks spec.

Seems so.

**Comment by Totktonada** [comment]
6ce9356f2c927c45225794cb3c407e8ea2cff36c
