### ISSUE TITLE
Array validation support

### ISSUE THREAD

**Issue by olegrok** [tarantool/checks#7]
Would like to be able to check the format of array elements

E.g. 
```
checks({ {id = 'number', value='?table' } })
```
Check all elements of input array

**Comment by ASverdlov** [comment]
Hey! Why not implement your own [custom checker](https://github.com/tarantool/checks#a-type-checking-function-name) for that?

**Comment by olegrok** [comment]
I think it's not specific need and it should be in the basic functionality of 'checks'.

It would be nice to have a universal solution to this problem, rather than writing something custom.

**Comment by rosik** [comment]
The syntax you've provided as an example is already used for checking table keys:
```
function foo(opts)
    checks({ {id = 'number', value='?table' } })
end
foo({ {id = 5} }) -- ok
```

You can even check arrays with specified number of elements this way. I know it's not what you've been asking for, but it's the way the checks work now. 
```
function bar(array)
    checks({'number', '?number'})
end
bar({1}) -- ok
bar({1, 2}) -- ok
bar({1, 2, 3}) -- error
```

In your case I think there is no other solution but implementing something like `checks('array_of_strings')` custom checker as ASverdlov adviced.

**Comment by rosik** [comment]
How about extending the syntax:

```lua
checks('{string}') -- array of strings
checks('?{string}') -- nil or box.NULL or array of strings
```

To be consistent, here are some weird corner cases

```lua
checks('string|{string}') -- ether a single sting or array of strings
checks('{string}|{number}') -- either array full of strings or array full of numbers
checks('{string|number}') -- array of strings or numbers (maybe mixed)
```

It's also important to decide what is "array".

I think the most useful check is whether lua table can be traversed with `ipairs` without losing a key.

So, my proposal is to implement it in the following manner:

```lua
function is_array(tbl)
    local i = 0
    for _ in pairs(tbl) do
        i = i + 1
        if tbl[i] == nil then
            return false
        end
    end
    return true
end
```

To avoid problems with the definition, expression `checks('{?string}')` should be treated as "array of box.NULL or strings (excluding nil)". But it's weird and I hope nobody will use it.

Further syntax extension may be used to check maps:

```lua
checks('{[string]=number}') -- table with string keys and numeric values
```  

P.S. The inspiration came from `ldoc` [documentation](https://stevedonovan.github.io/ldoc/manual/doc.md.html#Tag_Modifiers)

**Comment by olegrok** [comment]
I think your idea is good

Let's try to implement it

**Comment by Totktonada** [comment]
See also https://github.com/tarantool/tarantool/issues/2765#issuecomment-496731242

**Comment by Totktonada** [comment]
Is not it beyond the problem of arguments type checking? The proposal looks more like validation of an untrusted input. Oleg, do you have some motivating examples?

**Comment by olegrok** [comment]
Currently I don't even know. Probably we could add checks like "[string]" that could mean array of string. But issue is too ancient and I'm not sure it's relevant for me now. Feel free to close.

**Comment by filonenko-mikhail** [comment]
Gently closing
