### ISSUE TITLE
Use jit facilities to speedup the check

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/checks#9]
A special checker can be prepared as a plain lua code and compiled with a `loadstring` for each function.
There are two possible apis for that:
1. dis: you need to pass args to `checker`
```
checker = prepare_checker(arg description)
function my_func(args)
   checker(args)
   do_stuff
end
```

2. dis: I do not know how to retrieve the arg names (possibly should be described explicitly.
```
function my_func = check_args(arg description, fucntion (args)
   do_stuff
end
```

This method is possibly 100-1000x faster, here is a snippet:
```
N = 1000 * 1000 * 10

local i = 0
local function do_stuff()
    i = i + 1
end

local function check_jit1()
    local argname, value = debug.getlocal(2, 1)
    if type(value) ~= 'string' then
        error('lol ' .. tostring(value))
    end
    local argname, value = debug.getlocal(2, 2)
    if type(value) ~= 'string' then
        error('lol')
    end
end


local function check_simple1(...)
    local arg = {...}
    for i = 1, table.maxn(arg) do
        local expected_type = arg[i]
        local argname, value = debug.getlocal(2, i)
        if type(value) ~= expected_type then
            error('lol')
        end
    end
end

local function test_jit(a, b)
    check_jit1()
    do_stuff()
end


local function do_stuff_2()
    do_stuff()
end

local function test_jit2(a, b)
    if type(a) ~= 'string' then
        error('lol ')
    end
    if type(b) ~= 'string' then
        error('lol')
    end
    do_stuff_2(a, b)
end

local function test_simple(a, b)
    check_simple1('string', 'string')
    do_stuff()
end


nClock = os.clock()
for i = 1, N do
    test_jit("a", "b")
end
print( string.format("jit | t/n = %f", (os.clock()-nClock) / N * 10^9))

nClock = os.clock()
for i = 1, N do
    test_jit2("a", "b")
end
print( string.format("jit2 | t/n = %f", (os.clock()-nClock) / N * 10^9))

nClock = os.clock()
for i = 1, N do
    test_simple("a", "b")
end
print( string.format("simple | t/n = %f", (os.clock()-nClock)/N*10^9))
os.exit()
```
results
```
jit | t/n = 370.788700                         
jit2 | t/n = 1.318700                          
simple | t/n = 615.682200 
```

**Comment by racktear** [comment]
To be honest, I don't understand what you're trying to say here. Could you please clarify?

**Comment by Khatskevich** [comment]
The suggestion is to generate special check functions for each check statement by a provided format.
This approach allows the jit compiler to use more aggressive optimizations.

The idea is the same as in our Avro module.

**Comment by racktear** [comment]
What's the point? Did it prove to be slow in any of your cases?
I mean, this module is simple, obvious and readable. I suggest to not change it without serious reason.

**Comment by Khatskevich** [comment]
According to test results, current check time is ~600 ns.
It can be decreased to ~1 ns.

It will allow adding a check to any function you want without concerns about performance.

**Comment by racktear** [comment]
There is no point in creating a statically typed language from Lua. checks() should be mostly used on the public module API, where 600 ns is reasonable.

**Comment by rosik** [comment]
The slowest part of checks is `debug.getlocal` call. The only way to eliminate it is to pass arguments to a check statement explicitly, which is a huge API change. Such a refactoring would produce a different module with its own syntax and features, so I'm closing the issue.
